import { useState } from 'react';
import { WORD_FAMILIES, pickWordFormation } from '../data/wordFamilies';
import { useShuffleBag, useTimer } from '../utils/hooks';
import { useStats } from '../context/StatsContext';
import { normalize } from '../utils/helpers';

export function WordFormationPractice() {
  const nextIdx = useShuffleBag(WORD_FAMILIES.length);
  const [item, setItem] = useState(() => pickWordFormation(nextIdx()));
  const [value, setValue] = useState("");
  const [checked, setChecked] = useState(false);
  const { record, addMistake } = useStats();
  const timer = useTimer();

  function next() {
    setItem(pickWordFormation(nextIdx()));
    setValue("");
    setChecked(false);
    timer.reset();
  }
  function check() {
    const correct = normalize(value) === normalize(item.answer);
    if (!correct) addMistake({ key: "wf:" + item.capitals, term: item.text, meaning: item.answer, category: "Word Formation" });
    record("Word Formation", correct ? 1 : 0, correct ? 0 : 1, timer.elapsed());
    setChecked(true);
  }
  const isCorrect = checked && normalize(value) === normalize(item.answer);

  return (
    <div>
      <p className="text-sm text-ink/60 dark:text-paper/60 mb-6 max-w-prose">
        Generated by combining the word-family bank ({WORD_FAMILIES.length} words) with sentence templates — nothing repeats until every word has appeared once.
      </p>
      <p className="font-serif text-xl mb-4">{item.text}</p>
      <p className="text-xs font-mono text-ink/40 dark:text-paper/40 mb-4">{item.capitals}</p>
      {!checked ? (
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="Type the correct form"
            className="flex-1 px-3 py-2 rounded border border-ink/20 dark:border-paper/20 bg-transparent text-sm focus:outline-none focus:ring-2 focus:ring-gold"
          />
          <button onClick={check} className="px-4 py-2 rounded bg-ink dark:bg-paper text-paper dark:text-ink text-sm font-medium">
            Check
          </button>
        </div>
      ) : (
        <div className={"p-3 rounded border text-sm " + (isCorrect ? "border-teal bg-teal/10 text-teal" : "border-coral bg-coral/10 text-coral")}>
          <p className="font-medium">{isCorrect ? "Correct" : "Answer: " + item.answer}</p>
        </div>
      )}
      <button onClick={next} className="mt-4 text-sm font-medium text-ink/50 dark:text-paper/50 hover:underline">
        New exercise →
      </button>
    </div>
  );
}

